version: "2"
services:
  mysql:
    image: 'mysql:5.6.35'
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: docker
  php: 
    image: php:7.0-fpm
    links: 
      - mysql:mysqldb
    volumes: 
      - ./:/var/www/html
  apache: 
    build: dockerfiles
    links: 
      - php:phpfpm 
    volumes: 
      - ./:/var/www/html